-- Revive HealthScope: Pharmacy supplier / expiry returns
-- Run once in Supabase SQL Editor before using the Purchase Returns module.

create table if not exists public.pharmacy_purchase_returns (
  id bigint generated by default as identity primary key,
  stock_id text not null,
  purchase_id text,
  return_date date not null default current_date,
  category text,
  medicine_name text not null,
  batch_no text,
  expiry_date date,
  supplier_name text,
  quantity_returned numeric not null check (quantity_returned > 0),
  purchase_cost_per_unit numeric not null default 0,
  return_value numeric not null default 0,
  reason text not null,
  credit_note_no text,
  remarks text,
  created_by text,
  created_at timestamptz not null default now()
);

create index if not exists idx_pharmacy_purchase_returns_stock_id
  on public.pharmacy_purchase_returns(stock_id);
create index if not exists idx_pharmacy_purchase_returns_date
  on public.pharmacy_purchase_returns(return_date desc);
create index if not exists idx_pharmacy_purchase_returns_expiry
  on public.pharmacy_purchase_returns(expiry_date);

-- One transaction: validate batch quantity, reduce pharmacy_stock, and save the audit record.
create or replace function public.return_pharmacy_stock(
  p_stock_id text,
  p_purchase_id text,
  p_return_date date,
  p_supplier_name text,
  p_quantity numeric,
  p_reason text,
  p_credit_note_no text default null,
  p_remarks text default null,
  p_created_by text default null
)
returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
  s record;
  new_return_id bigint;
begin
  if p_quantity is null or p_quantity <= 0 then
    raise exception 'Return quantity must be greater than zero.';
  end if;

  select * into s
  from public.pharmacy_stock
  where id::text = p_stock_id
  for update;

  if not found then
    raise exception 'Stock batch not found.';
  end if;

  if coalesce(s.quantity,0) < p_quantity then
    raise exception 'Return quantity (%) exceeds available stock (%).', p_quantity, coalesce(s.quantity,0);
  end if;

  update public.pharmacy_stock
  set quantity = coalesce(quantity,0) - p_quantity
  where id::text = p_stock_id;

  insert into public.pharmacy_purchase_returns (
    stock_id,purchase_id,return_date,category,medicine_name,batch_no,expiry_date,
    supplier_name,quantity_returned,purchase_cost_per_unit,return_value,reason,
    credit_note_no,remarks,created_by
  ) values (
    p_stock_id,nullif(p_purchase_id,''),coalesce(p_return_date,current_date),
    s.category,s.medicine_name,s.batch_no,s.expiry_date,p_supplier_name,
    p_quantity,coalesce(s.purchase_price,0),p_quantity*coalesce(s.purchase_price,0),
    p_reason,nullif(p_credit_note_no,''),nullif(p_remarks,''),p_created_by
  ) returning id into new_return_id;

  return new_return_id;
end;
$$;

grant execute on function public.return_pharmacy_stock(text,text,date,text,numeric,text,text,text,text) to anon, authenticated;
grant select, insert on public.pharmacy_purchase_returns to anon, authenticated;
grant usage, select on sequence public.pharmacy_purchase_returns_id_seq to anon, authenticated;
