const VIEWS={dashboard:{title:"Dashboard",subtitle:"Live hospital overview",render:loadDashboard},patientSearch:{title:"Patient Search",subtitle:"Search records",render:renderPatientSearch},cashReport:{title:"Cash Report",subtitle:"Supabase daily cash book",render:renderCashReport},reports:{title:"Reports",subtitle:"Reports foundation",render:()=>placeholder("reportsView","Reports module will be built next.")},opd:{title:"OPD",subtitle:"Staff only",render:()=>placeholder("opdView","OPD v2 module will be built next.")},ipd:{title:"IPD",subtitle:"Staff only",render:()=>placeholder("ipdView","IPD v2 module will be built next.")},pharmacyStock:{title:"Pharmacy Stock",subtitle:"Pharmacy owner only",render:renderPharmacyStock},purchaseRegister:{title:"Purchase Register",subtitle:"Pharmacy purchase and stock entry",render:renderPurchaseRegister},supplierMaster:{title:"Supplier Master",subtitle:"Supplier directory",render:renderSupplierMaster},medicineMaster:{title:"Medicine Master",subtitle:"Standard medicine list",render:renderMedicineMaster},pharmacyBilling:{title:"Pharmacy Billing",subtitle:"Pharmacy staff only",render:()=>placeholder("pharmacyBillingView","Pharmacy billing v2 module will be built next.")},expenses:{title:"Expenses",subtitle:"Accountant only",render:()=>placeholder("expensesView","Expenses v2 module will be built next.")}};
function setVisibleView(name){document.querySelectorAll(".view").forEach(v=>v.classList.add("hidden"));document.getElementById(name+"View")?.classList.remove("hidden")}
async function navigate(name){const v=VIEWS[name];if(!v)return;document.getElementById("pageTitle").textContent=v.title;document.getElementById("pageSubtitle").textContent=v.subtitle;setVisibleView(name);document.querySelectorAll("#mainNav button").forEach(b=>b.classList.toggle("active",b.dataset.view===name));await v.render()}
function navForRole(role){const base=(NAV_BY_ROLE[role]||[]).slice();if(role==="pharmacyOwner"){["supplierMaster","medicineMaster"].forEach(x=>{if(!base.includes(x))base.push(x)})}if(role==="accountant"&&!base.includes("supplierMaster")){base.splice(2,0,"supplierMaster")}return base}
function buildNav(){const nav=document.getElementById("mainNav");nav.innerHTML="";navForRole(currentUser.role).forEach(k=>{const b=document.createElement("button");b.textContent=VIEWS[k].title;b.dataset.view=k;b.onclick=()=>navigate(k);nav.appendChild(b)})}
function showApp(){document.getElementById("loginPage").classList.add("hidden");document.getElementById("appShell").classList.remove("hidden");document.getElementById("roleBadge").textContent=ROLE_LABELS[currentUser.role];buildNav();navigate(navForRole(currentUser.role)[0]||"dashboard")}
document.getElementById("loginForm").addEventListener("submit",e=>{e.preventDefault();const user=login(document.getElementById("username").value,document.getElementById("password").value);if(!user){document.getElementById("loginError").textContent="Invalid username or password.";return}showApp()});
document.getElementById("logoutBtn").onclick=()=>{logout();location.reload()};
if(restoreSession())showApp();
