-- Optional ledger for individual IPD advance top-ups.
-- The app works without this table by updating ipd_admission.deposit_amount/advance.
create table if not exists public.ipd_advance_transactions (
  id bigint generated by default as identity primary key,
  admission_id text not null,
  admission_row_id bigint,
  uhid text,
  patient_name text,
  amount numeric(12,2) not null check (amount > 0),
  payment_mode text,
  transaction_date date not null default current_date,
  reference_no text,
  remarks text,
  transaction_type text not null default 'Top-Up',
  created_at timestamptz not null default now()
);
create index if not exists ipd_advance_transactions_admission_id_idx on public.ipd_advance_transactions(admission_id);
create index if not exists ipd_advance_transactions_date_idx on public.ipd_advance_transactions(transaction_date);
