-- Revive HealthScope: supplier / expiry returns
create table if not exists public.pharmacy_purchase_returns (
  id bigint generated by default as identity primary key,
  stock_id bigint not null,
  purchase_id bigint,
  supplier_name text,
  medicine_name text not null,
  category text,
  batch_no text,
  expiry_date date,
  return_date date not null default current_date,
  quantity numeric not null check (quantity > 0),
  purchase_price numeric not null default 0,
  return_value numeric not null default 0,
  reason text not null,
  credit_note_no text,
  remarks text,
  returned_by text,
  created_at timestamptz not null default now()
);

create index if not exists pharmacy_purchase_returns_stock_id_idx on public.pharmacy_purchase_returns(stock_id);
create index if not exists pharmacy_purchase_returns_return_date_idx on public.pharmacy_purchase_returns(return_date desc);

alter table public.pharmacy_purchase_returns enable row level security;

drop policy if exists "pharmacy returns read" on public.pharmacy_purchase_returns;
create policy "pharmacy returns read" on public.pharmacy_purchase_returns for select using (true);
drop policy if exists "pharmacy returns insert" on public.pharmacy_purchase_returns;
create policy "pharmacy returns insert" on public.pharmacy_purchase_returns for insert with check (true);

create or replace function public.return_pharmacy_stock(
  p_stock_id bigint,
  p_quantity numeric,
  p_return_date date,
  p_reason text,
  p_credit_note_no text default null,
  p_remarks text default null,
  p_returned_by text default null
) returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
  s public.pharmacy_stock%rowtype;
  p public.pharmacy_purchases%rowtype;
  v_id bigint;
begin
  if p_quantity is null or p_quantity <= 0 then raise exception 'Return quantity must be greater than zero'; end if;
  select * into s from public.pharmacy_stock where id=p_stock_id for update;
  if not found then raise exception 'Stock batch not found'; end if;
  if p_quantity > coalesce(s.quantity,0) then raise exception 'Return quantity exceeds available stock'; end if;
  select * into p from public.pharmacy_purchases
    where lower(coalesce(medicine_name,''))=lower(coalesce(s.medicine_name,''))
      and lower(coalesce(batch_no,''))=lower(coalesce(s.batch_no,''))
    order by created_at desc limit 1;

  insert into public.pharmacy_purchase_returns(stock_id,purchase_id,supplier_name,medicine_name,category,batch_no,expiry_date,return_date,quantity,purchase_price,return_value,reason,credit_note_no,remarks,returned_by)
  values(s.id,p.id,p.supplier_name,s.medicine_name,s.category,s.batch_no,s.expiry_date,coalesce(p_return_date,current_date),p_quantity,coalesce(s.purchase_price,0),p_quantity*coalesce(s.purchase_price,0),p_reason,nullif(trim(p_credit_note_no),''),nullif(trim(p_remarks),''),p_returned_by)
  returning id into v_id;

  update public.pharmacy_stock set quantity=quantity-p_quantity where id=s.id;
  return v_id;
end;
$$;

grant execute on function public.return_pharmacy_stock(bigint,numeric,date,text,text,text,text) to anon, authenticated;
