let returnStockRows=[];
function returnExpiryState(date){if(!date)return '';const d=new Date(date+'T00:00:00'),now=new Date();now.setHours(0,0,0,0);const days=Math.ceil((d-now)/86400000);if(days<0)return 'Expired';if(days<=90)return `Near Expiry (${days}d)`;return '';}
async function renderPharmacyReturns(){
 const el=document.getElementById('pharmacyReturnsView');
 el.innerHTML=`<div class="panel"><div class="form-row"><div><label>Search Stock</label><input id="returnStockSearch" placeholder="Medicine / batch / type"></div><div><label>Status</label><select id="returnExpiryFilter"><option value="eligible">Expired & Near Expiry</option><option value="all">All Stock</option><option value="expired">Expired Only</option><option value="near">Near Expiry Only</option></select></div></div></div>
 <div id="returnFormPanel" class="panel hidden"><h3>Return to Supplier</h3><div id="returnSelectedInfo" class="sync-box"></div><div class="grid" style="grid-template-columns:repeat(3,1fr)"><div><label>Return Quantity</label><input id="returnQty" type="number" min="0.01" step="0.01"></div><div><label>Return Date</label><input id="returnDate" type="date" value="${todayISO()}"></div><div><label>Reason</label><select id="returnReason"><option>Near Expiry</option><option>Expired</option><option>Damaged</option><option>Supplier Recall</option><option>Other</option></select></div><div><label>Credit Note No.</label><input id="returnCreditNote"></div><div style="grid-column:span 2"><label>Remarks</label><input id="returnRemarks"></div></div><br><button id="confirmReturnBtn" type="button">Confirm Return</button> <button id="cancelReturnBtn" type="button" class="secondary">Cancel</button><div id="returnMessage"></div></div>
 <div class="panel table-wrap"><h3>Stock Eligible for Return</h3><table><thead><tr><th>Item</th><th>Type</th><th>Batch</th><th>Expiry</th><th>Status</th><th>Available</th><th>Purchase Cost</th><th>Action</th></tr></thead><tbody id="returnStockBody"></tbody></table></div>
 <div class="panel table-wrap"><h3>Purchase Returns Register</h3><table><thead><tr><th>Date</th><th>Supplier</th><th>Item</th><th>Batch</th><th>Expiry</th><th>Qty</th><th>Value</th><th>Reason</th><th>Credit Note</th><th>User</th></tr></thead><tbody id="returnRegisterBody"></tbody></table></div>`;
 document.getElementById('returnStockSearch').oninput=drawReturnStock;
 document.getElementById('returnExpiryFilter').onchange=drawReturnStock;
 document.getElementById('cancelReturnBtn').onclick=()=>document.getElementById('returnFormPanel').classList.add('hidden');
 document.getElementById('confirmReturnBtn').onclick=savePharmacyReturn;
 await loadReturnStock();await loadReturnRegister();
}
async function loadReturnStock(){const {data,error}=await db.from('pharmacy_stock').select('*').gt('quantity',0).order('expiry_date',{ascending:true});const body=document.getElementById('returnStockBody');if(error){body.innerHTML=`<tr><td colspan="8" class="error">${error.message}</td></tr>`;return}returnStockRows=data||[];drawReturnStock()}
function drawReturnStock(){const body=document.getElementById('returnStockBody');if(!body)return;const q=(document.getElementById('returnStockSearch')?.value||'').trim().toLowerCase(),f=document.getElementById('returnExpiryFilter')?.value||'eligible';let rows=returnStockRows.filter(r=>[r.medicine_name,r.batch_no,r.category].join(' ').toLowerCase().includes(q));rows=rows.filter(r=>{const s=returnExpiryState(r.expiry_date);if(f==='all')return true;if(f==='expired')return s==='Expired';if(f==='near')return s.startsWith('Near Expiry');return s==='Expired'||s.startsWith('Near Expiry')});body.innerHTML=rows.length?rows.map(r=>{const s=returnExpiryState(r.expiry_date);return `<tr><td>${r.medicine_name||''}</td><td>${r.category||''}</td><td>${r.batch_no||''}</td><td>${r.expiry_date||''}</td><td>${s||'-'}</td><td>${r.quantity||0}</td><td>${money(r.purchase_price||0)}</td><td><button type="button" onclick="openPharmacyReturn('${r.id}')">Return</button></td></tr>`}).join(''):`<tr><td colspan="8">No matching stock.</td></tr>`}
function openPharmacyReturn(id){const r=returnStockRows.find(x=>String(x.id)===String(id));if(!r)return;window.__returnStock=r;const s=returnExpiryState(r.expiry_date);document.getElementById('returnSelectedInfo').innerHTML=`<b>${r.medicine_name||''}</b> · Batch ${r.batch_no||'-'} · Expiry ${r.expiry_date||'-'} · Available ${r.quantity||0}`;document.getElementById('returnQty').value=r.quantity||0;document.getElementById('returnQty').max=r.quantity||0;document.getElementById('returnReason').value=s==='Expired'?'Expired':s.startsWith('Near Expiry')?'Near Expiry':'Other';document.getElementById('returnCreditNote').value='';document.getElementById('returnRemarks').value='';document.getElementById('returnMessage').innerHTML='';document.getElementById('returnFormPanel').classList.remove('hidden');document.getElementById('returnFormPanel').scrollIntoView({behavior:'smooth',block:'start'})}
async function savePharmacyReturn(){const r=window.__returnStock,msg=document.getElementById('returnMessage');if(!r){msg.innerHTML="<p class='error'>Select a stock batch.</p>";return}const qty=Number(document.getElementById('returnQty').value||0);if(qty<=0||qty>Number(r.quantity||0)){msg.innerHTML="<p class='error'>Enter a valid return quantity within available stock.</p>";return}const btn=document.getElementById('confirmReturnBtn');btn.disabled=true;try{const {data,error}=await db.rpc('return_pharmacy_stock',{p_stock_id:r.id,p_quantity:qty,p_return_date:document.getElementById('returnDate').value||todayISO(),p_reason:document.getElementById('returnReason').value,p_credit_note_no:document.getElementById('returnCreditNote').value||null,p_remarks:document.getElementById('returnRemarks').value||null,p_returned_by:currentUser?.name||currentUser?.username||''});if(error){msg.innerHTML=`<p class='error'>Return failed: ${error.message}. Run pharmacy-returns.sql in Supabase SQL Editor if the return function is not installed.</p>`;return}msg.innerHTML=`<p class='success'>Return recorded successfully. Return No. ${data}. Stock has been reduced.</p>`;window.__returnStock=null;await loadReturnStock();await loadReturnRegister();setTimeout(()=>document.getElementById('returnFormPanel').classList.add('hidden'),1200)}finally{btn.disabled=false}}
async function loadReturnRegister(){const body=document.getElementById('returnRegisterBody'),{data,error}=await db.from('pharmacy_purchase_returns').select('*').order('created_at',{ascending:false});if(error){body.innerHTML=`<tr><td colspan="10" class="error">Returns register unavailable: ${error.message}</td></tr>`;return}const rows=data||[];body.innerHTML=rows.length?rows.map(r=>`<tr><td>${r.return_date||rowDate(r)}</td><td>${r.supplier_name||'-'}</td><td>${r.medicine_name||''}</td><td>${r.batch_no||''}</td><td>${r.expiry_date||''}</td><td>${r.quantity||0}</td><td>${money(r.return_value||0)}</td><td>${r.reason||''}</td><td>${r.credit_note_no||'-'}</td><td>${r.returned_by||'-'}</td></tr>`).join(''):`<tr><td colspan="10">No purchase returns recorded.</td></tr>`}
