-- Revive HealthScope: patient/customer medicine returns
-- Run once in Supabase SQL Editor.

create table if not exists public.pharmacy_customer_returns (
  id bigint generated by default as identity primary key,
  sale_id bigint not null,
  patient_name text,
  bill_date date,
  return_date date not null default current_date,
  reason text,
  refund_mode text not null default 'Cash',
  refund_amount numeric not null default 0,
  returned_by text,
  processed_by text,
  remarks text,
  created_at timestamptz not null default now()
);

create table if not exists public.pharmacy_customer_return_items (
  id bigint generated by default as identity primary key,
  return_id bigint not null references public.pharmacy_customer_returns(id) on delete cascade,
  sale_id bigint not null,
  stock_id bigint not null,
  medicine_name text not null,
  batch_no text,
  expiry_date date,
  quantity numeric not null check (quantity > 0),
  sale_price numeric not null default 0,
  refund_amount numeric not null default 0,
  item_condition text not null,
  restocked boolean not null default false,
  created_at timestamptz not null default now()
);

create index if not exists pharmacy_customer_returns_sale_idx on public.pharmacy_customer_returns(sale_id, created_at desc);
create index if not exists pharmacy_customer_return_items_sale_stock_idx on public.pharmacy_customer_return_items(sale_id, stock_id);

alter table public.pharmacy_customer_returns enable row level security;
alter table public.pharmacy_customer_return_items enable row level security;

drop policy if exists "customer returns read" on public.pharmacy_customer_returns;
create policy "customer returns read" on public.pharmacy_customer_returns for select using (true);
drop policy if exists "customer returns items read" on public.pharmacy_customer_return_items;
create policy "customer returns items read" on public.pharmacy_customer_return_items for select using (true);

create or replace function public.return_customer_medicines(
  p_sale_id bigint,
  p_items jsonb,
  p_return_date date,
  p_reason text,
  p_refund_mode text,
  p_returned_by text default null,
  p_processed_by text default null,
  p_remarks text default null
) returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
  s public.pharmacy_sales%rowtype;
  v_return_id bigint;
  v_item jsonb;
  v_stock_id bigint;
  v_qty numeric;
  v_condition text;
  v_original jsonb;
  v_original_qty numeric;
  v_sale_price numeric;
  v_already_returned numeric;
  v_medicine text;
  v_batch text;
  v_expiry date;
  v_refund numeric;
  v_total_refund numeric := 0;
  v_previous_refund numeric := 0;
begin
  select * into s from public.pharmacy_sales where id = p_sale_id for update;
  if not found then raise exception 'Original pharmacy bill not found'; end if;
  if p_items is null or jsonb_typeof(p_items) <> 'array' or jsonb_array_length(p_items)=0 then
    raise exception 'Select at least one medicine to return';
  end if;

  select coalesce(sum(refund_amount),0) into v_previous_refund
  from public.pharmacy_customer_returns where sale_id=p_sale_id;

  for v_item in select * from jsonb_array_elements(p_items)
  loop
    v_stock_id := nullif(v_item->>'stock_id','')::bigint;
    v_qty := coalesce(nullif(v_item->>'quantity','')::numeric,0);
    v_condition := coalesce(nullif(trim(v_item->>'condition'),''),'Sealed & reusable');
    if v_stock_id is null or v_qty <= 0 then raise exception 'Invalid return item'; end if;

    select x into v_original
    from jsonb_array_elements(coalesce(nullif(s.items_json,''),'[]')::jsonb) x
    where coalesce((x->>'__bill_meta')::boolean,false)=false
      and nullif(x->>'stock_id','')::bigint = v_stock_id
    limit 1;
    if v_original is null then raise exception 'Medicine batch is not part of the original bill'; end if;

    v_original_qty := coalesce((v_original->>'quantity')::numeric,0);
    v_sale_price := coalesce((v_original->>'sale_price')::numeric,0);
    v_medicine := coalesce(v_original->>'medicine_name','');
    v_batch := nullif(v_original->>'batch_no','');
    begin v_expiry := nullif(v_original->>'expiry_date','')::date; exception when others then v_expiry := null; end;

    select coalesce(sum(quantity),0) into v_already_returned
    from public.pharmacy_customer_return_items
    where sale_id=p_sale_id and stock_id=v_stock_id;

    if v_qty > (v_original_qty-v_already_returned) then
      raise exception 'Return quantity exceeds remaining returnable quantity for %', v_medicine;
    end if;

    v_refund := round(v_qty*v_sale_price,2);
    v_total_refund := v_total_refund + v_refund;
  end loop;

  if v_previous_refund + v_total_refund > coalesce(s.bill_amount,0) + 0.01 then
    raise exception 'Refund exceeds the amount paid on the original bill';
  end if;

  insert into public.pharmacy_customer_returns(
    sale_id,patient_name,bill_date,return_date,reason,refund_mode,refund_amount,returned_by,processed_by,remarks
  ) values(
    s.id,s.patient_name,s.bill_date,coalesce(p_return_date,current_date),nullif(trim(p_reason),''),
    coalesce(nullif(trim(p_refund_mode),''),'Cash'),v_total_refund,nullif(trim(p_returned_by),''),
    nullif(trim(p_processed_by),''),nullif(trim(p_remarks),'')
  ) returning id into v_return_id;

  for v_item in select * from jsonb_array_elements(p_items)
  loop
    v_stock_id := (v_item->>'stock_id')::bigint;
    v_qty := (v_item->>'quantity')::numeric;
    v_condition := coalesce(nullif(trim(v_item->>'condition'),''),'Sealed & reusable');
    select x into v_original
    from jsonb_array_elements(coalesce(nullif(s.items_json,''),'[]')::jsonb) x
    where coalesce((x->>'__bill_meta')::boolean,false)=false
      and nullif(x->>'stock_id','')::bigint = v_stock_id
    limit 1;
    v_sale_price := coalesce((v_original->>'sale_price')::numeric,0);
    v_medicine := coalesce(v_original->>'medicine_name','');
    v_batch := nullif(v_original->>'batch_no','');
    begin v_expiry := nullif(v_original->>'expiry_date','')::date; exception when others then v_expiry := null; end;
    v_refund := round(v_qty*v_sale_price,2);

    insert into public.pharmacy_customer_return_items(
      return_id,sale_id,stock_id,medicine_name,batch_no,expiry_date,quantity,sale_price,refund_amount,item_condition,restocked
    ) values(
      v_return_id,p_sale_id,v_stock_id,v_medicine,v_batch,v_expiry,v_qty,v_sale_price,v_refund,v_condition,
      lower(v_condition)='sealed & reusable'
    );

    if lower(v_condition)='sealed & reusable' then
      update public.pharmacy_stock set quantity=coalesce(quantity,0)+v_qty where id=v_stock_id;
      if not found then raise exception 'Original stock batch no longer exists for %', v_medicine; end if;
    end if;
  end loop;

  return v_return_id;
end;
$$;

grant execute on function public.return_customer_medicines(bigint,jsonb,date,text,text,text,text,text) to anon, authenticated;
