function hospitalBillHeader(title){return `<h2 style="text-align:center;margin:0">Revive Hospital</h2><p style="text-align:center;margin:4px 0 0">${title}</p><hr>`}
function openPrintWindow(content){const w=window.open("","_blank","width=900,height=700");w.document.write(`<html><head><title>Print</title><style>body{font-family:Arial;padding:24px;color:#111}table{width:100%;border-collapse:collapse}th,td{border-bottom:1px solid #ddd;padding:8px;text-align:left;font-size:13px}th{background:#f3f4f6}.grid{display:grid;gap:8px}@media print{button{display:none}}</style></head><body>${content}</body></html>`);w.document.close();w.focus();w.print()}
async function printOPDSlip(visitId){const visits=await fetchAll("opd_visits");const v=visits.find(x=>x.visit_id===visitId);if(!v){alert("OPD visit not found");return}openPrintWindow(`${hospitalBillHeader("OPD Slip")}<div class="grid" style="grid-template-columns:repeat(2,1fr)"><div><b>Visit ID:</b> ${v.visit_id||""}</div><div><b>Date:</b> ${v.visit_date||rowDate(v)}</div><div><b>UHID:</b> ${v.uhid||""}</div><div><b>Patient:</b> ${v.patient_name||""}</div><div><b>Age/Sex:</b> ${v.age||""} / ${v.sex||""}</div><div><b>Mobile:</b> ${v.mobile||""}</div><div><b>Department:</b> ${v.department||""}</div><div><b>Consultant:</b> ${v.consultant||""}</div><div><b>Visit Type:</b> ${v.visit_type||""}</div><div><b>Payment:</b> ${v.payment_mode||""}</div></div><h3 style="text-align:right">Amount: ${money(v.amount||0)}</h3>`)}
async function printDiagnosticsBill(billNo){const bills=await fetchAll("diagnostic_bills");const bill=bills.find(b=>b.bill_no===billNo);if(!bill){alert("Diagnostics bill not found");return}const {data:items}=await db.from("diagnostic_bill_items").select("*").eq("bill_no",billNo);const rows=(items||[]).map((i,idx)=>`<tr><td>${idx+1}</td><td>${i.test_name||""}</td><td>${money(i.price||0)}</td><td>${i.quantity||1}</td><td>${money(i.amount||0)}</td></tr>`).join("");openPrintWindow(`${hospitalBillHeader("Diagnostics Bill")}<div class="grid" style="grid-template-columns:repeat(2,1fr)"><div><b>Bill No:</b> ${bill.bill_no||""}</div><div><b>Date:</b> ${bill.billing_date||rowDate(bill)}</div><div><b>Patient:</b> ${bill.patient_name||""}</div><div><b>UHID:</b> ${bill.uhid||""}</div><div><b>Type:</b> ${bill.billing_type||""}</div><div><b>Payment:</b> ${bill.payment_mode||""}</div></div><br><table><thead><tr><th>#</th><th>Investigation</th><th>Rate</th><th>Qty</th><th>Amount</th></tr></thead><tbody>${rows}</tbody></table><h3 style="text-align:right">Total: ${money(bill.total_amount||0)}</h3>`)}
async function printPharmacyBill(id){const sales=await fetchAll("pharmacy_sales");const bill=sales.find(b=>String(b.id)===String(id));if(!bill){alert("Pharmacy bill not found");return}let items=[];try{items=JSON.parse(bill.items_json||"[]")}catch(e){items=[]}const rows=items.map((i,idx)=>`<tr><td>${idx+1}</td><td>${i.medicine_name||""}</td><td>${i.batch_no||""}</td><td>${i.expiry_date||""}</td><td>${i.quantity||0}</td><td>${money(i.sale_price||0)}</td><td>${money(i.total||0)}</td></tr>`).join("");openPrintWindow(`${hospitalBillHeader("Pharmacy Bill")}<div class="grid" style="grid-template-columns:repeat(2,1fr)"><div><b>Bill No:</b> PH-${bill.id||""}</div><div><b>Date:</b> ${bill.bill_date||rowDate(bill)}</div><div><b>Patient:</b> ${bill.patient_name||""}</div><div><b>Type:</b> ${bill.patient_type||""}</div><div><b>Payment:</b> ${bill.payment_mode||""}</div><div><b>Status:</b> ${bill.payment_status||""}</div></div><br><table><thead><tr><th>#</th><th>Medicine</th><th>Batch</th><th>Expiry</th><th>Qty</th><th>Rate</th><th>Amount</th></tr></thead><tbody>${rows}</tbody></table><h3 style="text-align:right">Total: ${money(bill.bill_amount||0)}</h3><p style="text-align:right"><b>Paid:</b> ${money(bill.amount_paid||0)} &nbsp; <b>Due:</b> ${money(bill.amount_due||0)}</p>`)}
function ipdBillEsc(v){return String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]))}
function ipdBillDate(v){if(!v)return"";const d=new Date(v);if(Number.isNaN(d.getTime()))return ipdBillEsc(v);return d.toLocaleDateString("en-IN",{day:"2-digit",month:"2-digit",year:"numeric"})}
function ipdAmountWords(n){const a=["","One","Two","Three","Four","Five","Six","Seven","Eight","Nine","Ten","Eleven","Twelve","Thirteen","Fourteen","Fifteen","Sixteen","Seventeen","Eighteen","Nineteen"],b=["","","Twenty","Thirty","Forty","Fifty","Sixty","Seventy","Eighty","Ninety"];function two(x){return x<20?a[x]:b[Math.floor(x/10)]+(x%10?" "+a[x%10]:"")}function three(x){return x<100?two(x):a[Math.floor(x/100)]+" Hundred"+(x%100?" "+two(x%100):"")}n=Math.round(Number(n)||0);if(n===0)return"Zero Rupees Only";let s="";const crore=Math.floor(n/10000000);n%=10000000;const lakh=Math.floor(n/100000);n%=100000;const thousand=Math.floor(n/1000);n%=1000;if(crore)s+=three(crore)+" Crore ";if(lakh)s+=two(lakh)+" Lakh ";if(thousand)s+=two(thousand)+" Thousand ";if(n)s+=three(n);return s.trim()+" Rupees Only"}
async function printIPDFinalBill(billId){
  const bills=await fetchAll("ipd_billing");const bill=bills.find(b=>b.bill_id===billId);if(!bill){alert("IPD bill not found");return}
  const [{data:items},{data:admissions}]=await Promise.all([db.from("ipd_bill_items").select("*").eq("bill_id",billId),db.from("ipd_admission").select("*").eq("admission_id",bill.admission_id)]);
  let adm=(admissions||[])[0];if(!adm){const all=await fetchAll("ipd_admission");adm=all.find(a=>String(a.id)===String(bill.admission_id)||String(a.admission_id)===String(bill.admission_id))||{}}
  const gross=Number(bill.gross_total??bill.total??0)||0,net=Number(bill.total??0)||0,discount=Math.max(0,gross-net),advance=Number(bill.advance||0)||0,finalPayment=Number(bill.final_payment||0)||0,refund=Number(bill.refund||0)||0,balance=Number(bill.balance||0)||0;
  const rows=(items||[]).map((i,idx)=>`<tr><td class="c">${idx+1}</td><td>${ipdBillEsc(i.category||"")}</td><td>${ipdBillEsc(i.description||"")}</td><td class="r">${money(i.rate||0)}</td><td class="c">${i.quantity||1}</td><td class="r">${money(i.amount||0)}</td></tr>`).join("");
  const w=window.open("","_blank","width=950,height=760");if(!w){alert("Please allow pop-ups for printing.");return}
  w.document.write(`<!doctype html><html><head><meta charset="utf-8"><title>Hospital Final Bill - ${ipdBillEsc(bill.patient_name||"")}</title><style>
  @page{size:A4 portrait;margin:10mm}*{box-sizing:border-box}body{margin:0;font-family:Arial,Helvetica,sans-serif;color:#111;font-size:11.5px;background:#fff}.sheet{max-width:190mm;margin:auto;border:1px solid #222;padding:7mm}.head{text-align:center;border-bottom:2px solid #111;padding-bottom:8px}.hospital{font-size:25px;font-weight:800;letter-spacing:.5px;text-transform:uppercase}.address{font-size:11px;margin-top:4px}.doc-title{font-size:17px;font-weight:800;text-align:center;margin:12px 0 9px;text-decoration:underline}.info{width:100%;border-collapse:collapse;margin-bottom:10px}.info td{border:1px solid #555;padding:6px 7px;width:25%;vertical-align:top}.lbl{font-size:9px;font-weight:700;text-transform:uppercase;color:#444;display:block;margin-bottom:2px}.val{font-size:11.5px;font-weight:600}.items{width:100%;border-collapse:collapse}.items th,.items td{border:1px solid #555;padding:6px}.items th{background:#eee;text-align:left;font-size:10px;text-transform:uppercase}.items .c{text-align:center}.items .r{text-align:right;white-space:nowrap}.summary{width:52%;margin:10px 0 0 auto;border-collapse:collapse}.summary td{border:1px solid #555;padding:6px}.summary td:last-child{text-align:right;font-weight:700}.summary .net td{font-size:13px;font-weight:800;border-top:2px solid #111}.words{border:1px solid #555;padding:7px;margin-top:10px;font-weight:700}.payment{margin-top:8px;display:flex;justify-content:space-between;gap:10px}.remarks{margin-top:8px;min-height:28px}.sign{display:flex;justify-content:space-between;align-items:flex-end;margin-top:28px}.sign>div{width:42%;text-align:center;border-top:1px solid #333;padding-top:4px}.footer{text-align:center;border-top:1px solid #777;margin-top:18px;padding-top:7px;font-size:10px}.muted{color:#555}@media print{body{font-size:11px}.sheet{border:1px solid #222;max-width:none}.items tr{break-inside:avoid}.summary{break-inside:avoid}}
  </style></head><body><div class="sheet"><div class="head"><div class="hospital">Revive Hospital</div><div class="address">Azamgarh, Uttar Pradesh</div></div><div class="doc-title">HOSPITAL FINAL BILL</div>
  <table class="info"><tr><td><span class="lbl">Patient Name</span><span class="val">${ipdBillEsc(bill.patient_name||adm.patient_name||"")}</span></td><td><span class="lbl">Age / Sex</span><span class="val">${ipdBillEsc([adm.age,adm.sex].filter(Boolean).join(" / ")||"—")}</span></td><td><span class="lbl">UHID</span><span class="val">${ipdBillEsc(bill.uhid||adm.uhid||"—")}</span></td><td><span class="lbl">Bill No.</span><span class="val">${ipdBillEsc(bill.bill_id||"")}</span></td></tr>
  <tr><td><span class="lbl">Admission ID</span><span class="val">${ipdBillEsc(bill.admission_id||adm.admission_id||"")}</span></td><td><span class="lbl">Date of Admission</span><span class="val">${ipdBillDate(adm.admission_date||adm.created_at)}</span></td><td><span class="lbl">Date of Discharge</span><span class="val">${ipdBillDate(adm.discharge_date||bill.billing_date)}</span></td><td><span class="lbl">Bill Date</span><span class="val">${ipdBillDate(bill.billing_date||bill.created_at)}</span></td></tr>
  <tr><td colspan="2"><span class="lbl">Consultant</span><span class="val">${ipdBillEsc(adm.doctor||adm.consultant||"—")}</span></td><td><span class="lbl">Ward / Bed</span><span class="val">${ipdBillEsc([adm.ward_type,adm.bed_no].filter(Boolean).join(" / ")||"—")}</span></td><td><span class="lbl">Payment Mode</span><span class="val">${ipdBillEsc(bill.payment_mode||"—")}</span></td></tr>
  ${adm.diagnosis?`<tr><td colspan="4"><span class="lbl">Diagnosis</span><span class="val">${ipdBillEsc(adm.diagnosis)}</span></td></tr>`:""}</table>
  <table class="items"><thead><tr><th style="width:6%">S.No.</th><th style="width:19%">Particular</th><th>Description</th><th style="width:14%">Rate</th><th style="width:8%">Qty</th><th style="width:15%">Amount</th></tr></thead><tbody>${rows||`<tr><td colspan="6" class="c">No bill items</td></tr>`}</tbody></table>
  <table class="summary"><tr><td>Gross Amount</td><td>${money(gross)}</td></tr>${discount>0?`<tr><td>Discount</td><td>- ${money(discount)}</td></tr>`:""}<tr class="net"><td>Net Bill Amount</td><td>${money(net)}</td></tr><tr><td>Advance Received</td><td>${money(advance)}</td></tr>${finalPayment>0?`<tr><td>Final Payment</td><td>${money(finalPayment)}</td></tr>`:""}${refund>0?`<tr><td>Refund</td><td>${money(refund)}</td></tr>`:""}${balance>0?`<tr><td>Balance Due</td><td>${money(balance)}</td></tr>`:""}</table>
  <div class="words"><span class="muted">Amount in words:</span> ${ipdAmountWords(net)}</div><div class="payment"><div><b>Payment Mode:</b> ${ipdBillEsc(bill.payment_mode||"—")}</div><div><b>Bill Status:</b> ${balance>0?"Balance Due":"PAID / SETTLED"}</div></div>${bill.remarks?`<div class="remarks"><b>Remarks:</b> ${ipdBillEsc(bill.remarks)}</div>`:""}<div class="sign"><div>Patient / Attendant Signature</div><div>Authorized Signatory<br><b>Revive Hospital</b></div></div><div class="footer">Thank you for choosing Revive Hospital</div></div><script>window.onload=()=>setTimeout(()=>window.print(),180);<\/script></body></html>`);w.document.close();w.focus();
}